tor-ci-linux, tor-ci-linux-clang: Print configure/make/check markers, and cat config.log if configure fails

diff --git a/slaves/linux/tor-ci-linux-clang/build b/slaves/linux/tor-ci-linux-clang/build
--- a/slaves/linux/tor-ci-linux-clang/build
+++ b/slaves/linux/tor-ci-linux-clang/build
@@ -3,6 +3,32 @@ set -x
 set -e
 
 ./autogen.sh
-./configure --enable-gcc-warnings --disable-silent-rules CC=clang
-make -k
-VERBOSE=yes make -k check
+
+echo "=== [build] running configure ==="
+./configure --enable-gcc-warnings --disable-silent-rules CC=clang && rc=0 || rc=$?
+if [ "$rc" != 0 ]; then
+  echo "=== [build] FAILED: configure ==="
+  echo >&2 "============================="
+  echo >&2 "Configure failed.  Trying to cat config.log."
+  echo >&2 "============================="
+  cat config.log || true
+  exit $rc
+fi
+
+echo "=== [build] running make ==="
+make -k ${TOR_JENKINS_MAKEFLAGS:-} && rc=0 || rc=$?
+if [ "$rc" != 0 ]; then
+  echo >&2 "============================="
+  echo >&2 "make -k failed.  Re-running without -k to maybe see the error near the end of the build-log."
+  echo >&2 "============================="
+  make ${TOR_JENKINS_MAKEFLAGS:-}
+  echo "=== [build] FAILED: make ==="
+  exit $rc
+fi
+
+echo "=== [build] running check ==="
+VERBOSE=yes make -k check && rc=0 || rc=$?
+if [ "$rc" != 0 ]; then
+  echo "=== [build] FAILED: check ==="
+  exit $rc
+fi
diff --git a/slaves/linux/tor-ci-linux/build b/slaves/linux/tor-ci-linux/build
--- a/slaves/linux/tor-ci-linux/build
+++ b/slaves/linux/tor-ci-linux/build
@@ -52,7 +52,19 @@ mkdir build-tree-tor RESULT
 
 (
 cd build-tree-tor
-../tor/configure "$@"
+
+echo "=== [build] running configure ==="
+../tor/configure "$@" && rc=0 || rc=$?
+if [ "$rc" != 0 ]; then
+  echo "=== [build] FAILED: configure ==="
+  echo >&2 "============================="
+  echo >&2 "Configure failed.  Trying to cat config.log."
+  echo >&2 "============================="
+  cat config.log || true
+  exit $rc
+fi
+
+echo "=== [build] running make ==="
 make -k ${TOR_JENKINS_MAKEFLAGS:-} && rc=0 || rc=$?
 if [ "$rc" != 0 ]; then
   echo >&2 "============================="
@@ -61,7 +73,14 @@ if [ "$rc" != 0 ]; then
   make ${TOR_JENKINS_MAKEFLAGS:-}
   exit $rc
 fi
-TOR_FUZZ_CORPORA=../fuzzing-corpora VERBOSE=yes make -k ${TOR_JENKINS_MAKEFLAGS:-} check
+
+echo "=== [build] running check ==="
+TOR_FUZZ_CORPORA=../fuzzing-corpora VERBOSE=yes make -k ${TOR_JENKINS_MAKEFLAGS:-} check && rc=0 || rc=$?
+if [ "$rc" != 0 ]; then
+  echo "=== [build] FAILED: check ==="
+  exit $rc
+fi
+
 )
 
 if [ -e build-tree-tor/src/or/tor ] ; then
