tor-ci-mingwcross-master: build log markers

diff --git a/slaves/linux/tor-ci-mingwcross-master/build b/slaves/linux/tor-ci-mingwcross-master/build
--- a/slaves/linux/tor-ci-mingwcross-master/build
+++ b/slaves/linux/tor-ci-mingwcross-master/build
@@ -30,6 +30,8 @@ done
 BASE="`pwd`"
 (cd tor
   ./autogen.sh
+
+  echo "=== [build] running configure ==="
   ./configure \
     --disable-silent-rules \
     --disable-asciidoc \
@@ -38,8 +40,28 @@ BASE="`pwd`"
     --with-openssl-dir="$BASE/UPSTREAM" \
     --with-zlib-dir="$BASE/UPSTREAM" \
     --prefix=/ \
-    --enable-gcc-warnings
-  make -k install DESTDIR="$BASE/RESULT"
+    --enable-gcc-warnings \
+    && rc=0 || rc=$?
+  if [ "$rc" != 0 ]; then
+    echo "=== [build] FAILED: configure ==="
+    echo >&2 "============================="
+    echo >&2 "Configure failed.  Trying to cat config.log."
+    echo >&2 "============================="
+    cat config.log || true
+    exit $rc
+  fi
+
+  echo "=== [build] running make ==="
+  make -k install DESTDIR="$BASE/RESULT" && rc=0 || rc=$?
+  if [ "$rc" != 0 ]; then
+    echo >&2 "============================="
+    echo >&2 "make -k failed.  Re-running without -k to maybe see the error near the end of the build-log."
+    echo >&2 "============================="
+    make install DESTDIR="$BASE/RESULT" || true
+    echo "=== [build] FAILED: make ==="
+    exit $rc
+  fi
+
   cp src/test/test.exe "$BASE/RESULT/bin/"
   cp src/test/test-child.exe "$BASE/RESULT/bin/"
 )
